# Generated by Django 5.0.7 on 2024-07-27 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='rest_def.jpg', upload_to='profile_pics/')),
                ('cover', models.ImageField(default='cover_def.jpg', upload_to='cover_pics/')),
                ('openTime', models.CharField(max_length=10)),
                ('closeTime', models.CharField(max_length=10)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('googleMaps', models.URLField(blank=True, null=True)),
                ('currency', models.CharField(default='TL', max_length=10)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pages.profile')),
            ],
        ),
    ]
