# Generated by Django 5.0.7 on 2024-07-27 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotdeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='hotDeal_def.jpg', upload_to='hotdeal_pics/')),
                ('description', models.TextField()),
                ('oldPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('newPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sender_id', models.IntegerField()),
                ('end_time', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عنوان الوجبة', max_length=100)),
                ('image', models.ImageField(default='meal_def.jpg', upload_to='product_pics/')),
                ('description', models.TextField(default='وصف الوجبة')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sender_id', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category')),
            ],
        ),
    ]
