# Generated by Django 5.0.7 on 2024-08-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdeals',
            name='buyingMassage',
            field=models.TextField(default='رسالة الشراء'),
        ),
        migrations.AddField(
            model_name='product',
            name='buyingMassage',
            field=models.TextField(default='رسالة الشراء'),
        ),
    ]
