# Generated by Django 4.2.11 on 2024-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_hotdeals_buyingmassage_product_buyingmassage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdeals',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
