# Generated by Django 4.2.11 on 2024-08-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_hotdeals_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotdeals',
            name='is_new',
        ),
    ]
